# Copyright (C) 2015, Redbeard Enterprises Ltd.
#
# Not to be used in any form without express written consent.
# All rights reserved.
#
# $Id: makefile 2 2010-03-29 03:41:56Z jason $

RUMPATH := ../redrum

STATICLIBS := module1  \
              module23

# define module directories to source objects from when building
# the above libs
module1  := src/module1
module23 := src/module2 src/module3

include $(RUMPATH)/target.mk
include $(RUMPATH)/lib.mk
